In [1]:
import scipy as sp
import numpy as np
import math

In [2]:
class four_vector:
    def __init__(self, t, x, y, z):
        self.four_vec = np.array([t,x,y,z], np.float32)
        
    def print_vector(vec):
        #print("["+str(round(vec.four_vec[0],2))+", "+str(round(vec.four_vec[1],2))+", "+str(round(vec.four_vec[2],2))+", "+str(round(vec.four_vec[3],2))+"] ")
        print("["+str(vec.four_vec[0])+", "+str(vec.four_vec[1])+", "+str(vec.four_vec[2])+", "+str(vec.four_vec[3])+"] ")
        #print("time:  " + str(round(vec.four_vec[0],2)))
        #print("x:     " + str(round(vec.four_vec[1],2)))
        #print("y:     " + str(round(vec.four_vec[2],2)))
        #print("z:     " + str(round(vec.four_vec[3],2))+"\n")

In [3]:
class four_matrix:
    def __init__(self):
        self.mat = np.identity(4)

    def minkowski(self):
        self.mat = np.array( [[1, 0, 0, 0],
                   [0, -1, 0, 0],
                   [0, 0, -1, 0],
                   [0, 0, 0, -1]])     
        
    def Xboost(self, vel):
        c = 299792458 #m/s
        gamma = 1/(sp.sqrt(1-((pow(vel,2))/(pow(c,2)))))

        self.mat = np.array([[gamma, -gamma*vel/c, 0, 0],
                             [-gamma*vel/c, gamma, 0, 0],
                             [0, 0, 1, 0],
                             [0, 0, 0, 1]])
        
    def Yboost(self, vel):
        c = 299792458 #m/s
        gamma = 1/(sp.sqrt(1-((pow(vel,2))/(pow(c,2)))))

        self.mat = np.array([[gamma, 0, -gamma*vel/c, 0],
                             [0, 1, 0, 0],
                             [-gamma*vel/c, 0, gamma, 0],
                             [0, 0, 0, 1]])
    def Zboost(self, vel):
        c = 299792458 #m/s
        gamma = 1/(sp.sqrt(1-((pow(vel,2))/(pow(c,2)))))

        self.mat = np.array([[gamma, 0, 0, -gamma*vel/c],
                             [0, 1, 0, 0],
                             [0, 0, 1, 0],
                             [-gamma*vel/c, 0, 0, gamma]])
     
    def Xrotation(self, angle):
        self.mat = np.array([[1, 0, 0, 0],
                             [0, 1, 0, 0],
                             [0, 0, np.cos(angle), -np.sin(angle)],
                             [0, 0, np.sin(angle), np.cos(angle)]])
    
    def Yrotation(self, angle):
        self.mat = np.array([[1, 0, 0, 0],
                             [0, np.cos(angle), 0, np.sin(angle)],
                             [0, 0, 1, 0],
                             [0, -np.sin(angle), 0, np.cos(angle)]])
        

    def Zrotation(self, angle):
        self.mat = np.array([[1, 0, 0, 0],
                             [0, np.cos(angle), -np.sin(angle), 0],
                             [0, np.sin(angle), np.cos(angle), 0],
                             [0, 0, 0, 1]])
    
    def lorentz(self, mink):
        Lorx = four_matrix()
        Lory = four_matrix()
        Lorz = four_matrix()
        
        Lorx.mat = self.mat.transpose()
        Lory.mat = np.matmul(Lorx.mat, mink.mat)
        Lorz.mat = np.matmul(Lory.mat, self.mat)
        
        return Lorz
    
    
    def print_matrix(self):
        print(self.mat)
    

$$X^\mu = \Lambda^\mu _{\nu}$$ 
 

$$\Lambda^T \eta \Lambda = \eta$$

In [4]:
def lorentz(prams):

    trans = []

    for i in range(7):
        trans.append(four_matrix())

    trans[0].Xboost(prams[0])
    trans[1].Yboost(prams[1])
    trans[2].Zboost(prams[2])
    trans[3].Xrotation(prams[3])
    trans[4].Yrotation(prams[4])
    trans[5].Zrotation(prams[5])

    for x in trans:
        trans[6].mat = np.matmul(trans[6].mat, x.mat)
    
    #trans[6].print_matrix()
    
    return trans[6]

$$X^\mu \eta_{\mu \nu} X^\nu = c^2t^2 - x^2 - y^2 - z^2$$ 

In [5]:
def invariant(x, mink):
    
    y = four_vector(0,0,0,0)
    
    y.four_vec = np.matmul(mink.mat, x.four_vec)
    invar = np.matmul(y.four_vec, x.four_vec)
    
    return invar

In [6]:
c = 299792458 #m/s

frame_prams = [0,0,0,np.pi/4,0,0]

minkowski = four_matrix()
minkowski.minkowski()

lor_tran = lorentz(frame_prams)

x = four_vector(0.0, 1.0, 2.0, 0.0)
y = four_vector(0,0,0,0)

y.four_vec = np.matmul(lor_tran.mat, x.four_vec)

four_vector.print_vector(x)
four_vector.print_vector(y)

#print(invariant(y, minkowski))
#print(round(invariant(x, minkowski),2))
#print(round(invariant(y, minkowski),2))

lor_tran.lorentz(minkowski).print_matrix()


[0.0, 1.0, 2.0, 0.0] 
[0.0, 1.0, 3.9934692350854785e-16, 2.0] 
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.00000000e+00  2.02930727e-17]
 [ 0.00000000e+00  0.00000000e+00  2.02930727e-17 -1.00000000e+00]]
